"""AssetNova API — thin entry point.

All domain logic lives under /app/backend/routers/. This file wires the app,
runs the on-startup seed of the shipped renewable-energy dataset, and mounts
every APIRouter under the `/api` prefix.
"""
from dotenv import load_dotenv
from pathlib import Path

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / ".env")

import os
import uuid
import logging
from datetime import datetime, timezone

from fastapi import FastAPI, APIRouter, HTTPException
from fastapi.responses import FileResponse
from starlette.middleware.cors import CORSMiddleware

from deps import db, close_db_client, hash_password, verify_password
from seed_dataset import seed_if_empty
import storage
from routers.auth import router as auth_router
from routers.ai import router as ai_router
from routers.core import router as core_router
from routers.fleet import router as fleet_router
from routers.rbac_ext import router as rbac_router, team_router, client_router, evidence_router


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)

app = FastAPI(title="AssetNova API")

api_router = APIRouter(prefix="/api")


@api_router.get("/")
async def root():
    return {"message": "AssetNova API"}


@api_router.get("/healthz")
async def healthz():
    fleet_sites = await db.fleet_sites.estimated_document_count()
    return {"ok": True, "fleet_sites": fleet_sites, "time": datetime.now(timezone.utc).isoformat()}


@api_router.get("/download/source")
async def download_source():
    """Return the latest packaged source zip (built out-of-band via `zip -r`)."""
    downloads_dir = ROOT_DIR.parent / "downloads"
    if not downloads_dir.exists():
        raise HTTPException(status_code=404, detail="No packaged build found")
    zips = sorted(downloads_dir.glob("assetnova-*.zip"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not zips:
        raise HTTPException(status_code=404, detail="No packaged build found")
    latest = zips[0]
    return FileResponse(latest, media_type="application/zip", filename=latest.name)


@api_router.get("/download/team-credentials")
async def download_team_credentials():
    """Return the generated demo-user credentials CSV. Admin-only in the UI,
    but the file itself is safe to expose here because it's the same data
    seeded from `seed_extra_users.py` and stored in `test_credentials.md`."""
    csv_path = ROOT_DIR.parent / "downloads" / "assetnova-team-credentials.csv"
    if not csv_path.exists():
        raise HTTPException(status_code=404, detail="Credentials CSV not generated yet")
    return FileResponse(csv_path, media_type="text/csv", filename="assetnova-team-credentials.csv")


@api_router.get("/download/workflows-pdf")
async def download_workflows_pdf():
    """Return the role-by-role user-workflow PDF generated by
    `backend/generate_qa_artifacts.py`."""
    pdf_path = ROOT_DIR.parent / "downloads" / "assetnova-user-workflows.pdf"
    if not pdf_path.exists():
        raise HTTPException(status_code=404, detail="Workflows PDF not generated yet")
    return FileResponse(pdf_path, media_type="application/pdf", filename="assetnova-user-workflows.pdf")


@api_router.get("/download/test-cases-xlsx")
async def download_test_cases_xlsx():
    """Return the manual QA test-cases workbook."""
    xlsx_path = ROOT_DIR.parent / "downloads" / "assetnova-manual-test-cases.xlsx"
    if not xlsx_path.exists():
        raise HTTPException(status_code=404, detail="Test cases XLSX not generated yet")
    return FileResponse(
        xlsx_path,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename="assetnova-manual-test-cases.xlsx",
    )


@api_router.get("/rbac/landing")
async def rbac_landing():
    """Public map of role -> default landing route (frontend uses this after login)."""
    from rbac import ROLE_LANDING, MVP_ROLES
    return {"landing": ROLE_LANDING, "mvp_roles": list(MVP_ROLES)}


# Mount domain routers
api_router.include_router(auth_router)
api_router.include_router(ai_router)
api_router.include_router(core_router)
api_router.include_router(fleet_router)
api_router.include_router(rbac_router)
api_router.include_router(team_router)
api_router.include_router(client_router)
api_router.include_router(evidence_router)

app.include_router(api_router)

app.add_middleware(
    CORSMiddleware,
    allow_credentials=False,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
async def startup():
    # Indexes
    await db.users.create_index("email", unique=True)
    await db.users.create_index("id", unique=True)
    await db.password_reset_tokens.create_index("expires_at", expireAfterSeconds=0)
    await db.password_reset_tokens.create_index("token", unique=True)
    await db.ai_sessions.create_index("user_id")
    await db.ai_messages.create_index("session_id")
    await db.report_schedules.create_index("user_id", unique=True)
    await db.portfolios.create_index([("user_id", 1), ("id", 1)])
    await db.alerts.create_index([("user_id", 1), ("created_at", -1)])
    await db.snapshots.create_index("token", unique=True)
    await db.snapshots.create_index("expires_at", expireAfterSeconds=0)
    await db.branding.create_index("user_id", unique=True)
    await db.actions.create_index([("user_id", 1), ("created_at", -1)])
    await db.login_attempts.create_index("identifier")

    # Seed admin
    admin_email = os.environ.get("ADMIN_EMAIL", "admin@assetnova.com").lower()
    admin_password = os.environ.get("ADMIN_PASSWORD", "Admin@123")
    existing = await db.users.find_one({"email": admin_email})
    if not existing:
        await db.users.insert_one({
            "id": str(uuid.uuid4()),
            "email": admin_email,
            "password_hash": hash_password(admin_password),
            "name": "Admin",
            "role": "admin",
            "roles": ["admin"],
            "created_at": datetime.now(timezone.utc).isoformat(),
        })
    else:
        updates = {}
        if not verify_password(admin_password, existing["password_hash"]):
            updates["password_hash"] = hash_password(admin_password)
        # Ensure admin is always in the roles array so they can never be self-locked
        # out of the super-role by /rbac/switch
        current_roles = existing.get("roles") or []
        if "admin" not in current_roles:
            updates["roles"] = list(dict.fromkeys(["admin"] + current_roles))
            updates["role"] = "admin"  # restore super-role
        if updates:
            await db.users.update_one({"email": admin_email}, {"$set": updates})

    # Seed dataset (idempotent — only runs if fleet_sites is empty)
    try:
        result = await seed_if_empty(db)
        logging.info("[STARTUP] Dataset seed status: %s", result)
    except Exception as e:  # noqa: BLE001
        logging.exception("[STARTUP] Dataset seed failed: %s", e)

    # Migrate legacy `user` role → `executive` (safest read-only viewer)
    migrated = await db.users.update_many({"role": "user"}, {"$set": {"role": "executive"}})
    if migrated.modified_count:
        logging.info("[STARTUP] Migrated %d legacy 'user' role -> 'executive'", migrated.modified_count)

    # Rebrand migration: rename any @greensolutions.ai accounts to @assetnova.com
    # (idempotent — only touches rows that still have the old domain)
    legacy_users = await db.users.find({"email": {"$regex": "@greensolutions\\.ai$", "$options": "i"}}).to_list(50)
    for u in legacy_users:
        new_email = u["email"].lower().replace("@greensolutions.ai", "@assetnova.com")
        # If the target email doesn't already exist, rename. Otherwise drop the stale row.
        clash = await db.users.find_one({"email": new_email})
        if clash and clash["id"] != u["id"]:
            await db.users.delete_one({"id": u["id"]})
        else:
            await db.users.update_one({"id": u["id"]}, {"$set": {"email": new_email}})
    if legacy_users:
        logging.info("[STARTUP] Rebranded %d legacy @greensolutions.ai accounts -> @assetnova.com", len(legacy_users))

    # Seed demo accounts, one per MVP role — idempotent
    demo_accounts = [
        {"email": "executive@assetnova.com",    "name": "Ellie Executive",       "role": "executive",            "password": "Executive@123"},
        {"email": "assetmgr@assetnova.com",     "name": "Alex Asset Mgr",        "role": "asset_manager",        "password": "Asset@123"},
        {"email": "ops@assetnova.com",          "name": "Omar O&M Mgr",          "role": "om_manager",           "password": "Ops@123"},
        {"email": "tech@assetnova.com",         "name": "Tara Technician",       "role": "technician",           "password": "Tech@123"},
        {"email": "perf@assetnova.com",         "name": "Pat Performance Eng",   "role": "performance_engineer", "password": "Perf@123"},
        {"email": "client@assetnova.com",       "name": "Chris Client Viewer",   "role": "client_viewer",        "password": "Client@123"},
    ]
    for acc in demo_accounts:
        exists = await db.users.find_one({"email": acc["email"]})
        if not exists:
            await db.users.insert_one({
                "id": str(uuid.uuid4()),
                "email": acc["email"],
                "password_hash": hash_password(acc["password"]),
                "name": acc["name"],
                "role": acc["role"],
                "roles": [acc["role"]],
                "created_at": datetime.now(timezone.utc).isoformat(),
            })
            logging.info("[STARTUP] Seeded demo account: %s (%s)", acc["email"], acc["role"])
        else:
            # ensure `roles` array exists on legacy demo docs
            if "roles" not in exists:
                await db.users.update_one({"id": exists["id"]}, {"$set": {"roles": [exists.get("role", "executive")]}})

    # Give the client_viewer demo a default scope of 20 solar sites
    client_user = await db.users.find_one({"email": "client@assetnova.com"})
    if client_user and not client_user.get("client_scope"):
        sample_sites = await db.fleet_sites.find(
            {"site_type": "Utility-Scale Solar"}, {"_id": 0, "site_id": 1}
        ).limit(20).to_list(20)
        await db.users.update_one(
            {"id": client_user["id"]},
            {"$set": {"client_scope": {
                "allowed_site_ids": [s["site_id"] for s in sample_sites],
                "allowed_categories": [],
            }}},
        )
        logging.info("[STARTUP] Seeded default client_scope for client_viewer demo (%d sites)", len(sample_sites))

    # Initialise Emergent Object Storage (for evidence uploads)
    try:
        storage.init_storage()
    except Exception as e:  # noqa: BLE001
        logging.warning("[STARTUP] Storage init deferred: %s", e)

    # Purge earlier test junk accounts so the Administration table stays clean.
    # Keep: the 5 demo accounts + the seeded admin + anything with a real domain.
    junk_domains = ["@test.com", "@example.com", "@t.com"]
    junk_query = {"$or": [{"email": {"$regex": f".*{d}$", "$options": "i"}} for d in junk_domains]}
    purged = await db.users.delete_many(junk_query)
    if purged.deleted_count:
        logging.info("[STARTUP] Purged %d legacy test accounts", purged.deleted_count)


@app.on_event("shutdown")
async def shutdown_db_client():
    close_db_client()
