export default function TermsOfUse() {
  const sections = [
    {
      t: "Acceptance of Terms",
      d: "By accessing or using the AssetNova™ platform, operated by AssetNova Energy™, you agree to be bound by these Terms of Use. If you do not agree, please do not use the platform.",
    },
    {
      t: "Use of the Platform",
      d: "AssetNova™ is provided for authorized use by permitted account holders to monitor, analyze, and manage renewable energy assets. You agree to use the platform only for lawful purposes and in accordance with these terms.",
    },
    {
      t: "Account Responsibilities",
      d: "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.",
    },
    {
      t: "Intellectual Property",
      d: "All content, branding, software, design, workflows, and dashboards within AssetNova™ are the property of AssetNova Energy™ or its licensors and may not be copied, reproduced, or distributed without prior written permission. See our Trademark Notice for further detail.",
    },
    {
      t: "Data & AI-Generated Insights",
      d: "Findings, recommendations, and reports generated by the platform are intended to support operational decision-making and do not constitute professional, engineering, or financial advice.",
    },
    {
      t: "Limitation of Liability",
      d: "AssetNova Energy™ shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform, to the fullest extent permitted by applicable law.",
    },
    {
      t: "Changes to These Terms",
      d: "We may revise these Terms of Use from time to time. Continued use of the platform after changes are posted constitutes acceptance of the revised terms.",
    },
    {
      t: "Contact",
      d: "Questions about these Terms of Use can be directed to info@assetnovaenergy.com.",
    },
  ];

  return (
    <div className="gs-canvas py-16 px-6 lg:px-14 min-h-[80vh]" data-testid="terms-of-use-page">
      <div className="max-w-[760px] mx-auto">
        <div className="eyebrow">LEGAL</div>
        <h1 className="font-display text-4xl md:text-5xl mt-4 leading-[1.05] text-[color:var(--ink)]">
          Terms of Use
        </h1>
        <p className="text-[color:var(--ink-3)] mt-4 text-sm font-mono">
          Last updated: {new Date().getFullYear()}
        </p>

        <div className="gs-card p-8 mt-10 space-y-8">
          {sections.map((s) => (
            <div key={s.t}>
              <h2 className="font-display text-lg text-[color:var(--ink)]">{s.t}</h2>
              <p className="mt-2 text-[15px] leading-relaxed text-[color:var(--ink-2)]">{s.d}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
